name = "expense-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"
[version_metadata]
binding = "CF_VERSION_METADATA"

[vars]
ADMIN_PASSWORD = ""
JWT_SECRET = "jwt-staging-secret-expense-api-2024"

[[d1_databases]]
binding = "DB"
database_name = "expense-db"
database_id = "1002bca0-397d-4065-897e-447b1d48cd2e"

# R2 is optional - uncomment to enable file storage
# [[r2_buckets]]
# binding = "BUCKET"
# bucket_name = "expense-files"

[env.review]
name = "expense-api-review"

[env.review.vars]
ADMIN_PASSWORD = "expense-review-2024"
JWT_SECRET = "jwt-review-secret-expense-api-2024"
ENVIRONMENT = "review"

[[env.review.d1_databases]]
binding = "DB"
database_name = "expense-db-review"
database_id = "56454cea-b4b8-4674-a8b0-134340ad7df0"

[dev]
port = 8788
